-- Drop existing adoptions table if it exists
DROP TABLE IF EXISTS public.adoptions;

-- Create rescued_animals table with proper schema
CREATE TABLE IF NOT EXISTS public.rescued_animals (
  id bigint generated by default as identity primary key,
  name text not null,
  species text not null,
  breed text,
  age int,
  image_url text,
  rescue_story text,
  health_status text,
  current_status text check (current_status in ('Available','Adopted','Under Care')) default 'Available',
  rescue_date date not null,
  created_at timestamp with time zone default now()
);

-- Create adoptions table with foreign key to rescued_animals
CREATE TABLE public.adoptions (
  id bigint generated by default as identity primary key,
  animal_id bigint references rescued_animals(id) on delete cascade,
  adopter_name text not null,
  contact_number text not null,
  aadhar_number char(12) check (aadhar_number ~ '^[0-9]{12}$'),
  email text not null check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
  already_have_pet boolean,
  reason text,
  adoption_date timestamp default now()
);

-- Enable RLS on both tables
ALTER TABLE public.rescued_animals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.adoptions ENABLE ROW LEVEL SECURITY;

-- RLS policies for rescued_animals
CREATE POLICY "Anyone can view rescued animals" ON public.rescued_animals
FOR SELECT USING (true);

CREATE POLICY "Anyone can insert rescued animals" ON public.rescued_animals
FOR INSERT WITH CHECK (true);

CREATE POLICY "Anyone can update rescued animals" ON public.rescued_animals
FOR UPDATE USING (true);

-- RLS policies for adoptions
CREATE POLICY "Anyone can view adoptions" ON public.adoptions
FOR SELECT USING (true);

CREATE POLICY "Anyone can submit adoptions" ON public.adoptions
FOR INSERT WITH CHECK (true);

-- Function to update animal status when adopted
CREATE OR REPLACE FUNCTION update_animal_status()
RETURNS trigger AS $$
BEGIN
  UPDATE rescued_animals
  SET current_status = 'Adopted'
  WHERE id = NEW.animal_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to run after insert on adoptions
CREATE TRIGGER after_adoption_insert
AFTER INSERT ON adoptions
FOR EACH ROW
EXECUTE FUNCTION update_animal_status();

-- Insert sample rescued animals data
INSERT INTO public.rescued_animals (name, species, breed, age, image_url, rescue_story, health_status, current_status, rescue_date) VALUES
('Buddy', 'Dog', 'Golden Retriever Mix', 3, '🐕', 'Buddy was found abandoned on the street, malnourished and scared. After weeks of care and rehabilitation, he has transformed into a loving, playful companion ready for his forever home.', 'Healthy - Fully vaccinated and neutered', 'Available', '2024-01-15'),
('Luna', 'Cat', 'Domestic Shorthair', 2, '🐱', 'Luna was rescued from a construction site where she had been living for months. She was very shy initially but has blossomed into an affectionate cat who loves gentle pets and sunny windowsills.', 'Healthy - Spayed and vaccinated', 'Available', '2024-02-20'),
('Max', 'Dog', 'Border Collie Mix', 5, '🐶', 'Max was surrendered by his previous owners who could no longer care for him. Despite this setback, he remains optimistic and intelligent, always eager to learn new tricks and go on adventures.', 'Healthy - All medical needs met', 'Available', '2024-03-10'),
('Whiskers', 'Cat', 'Maine Coon Mix', 4, '🐱', 'Whiskers was found injured after a car accident. Thanks to emergency surgery and months of recovery, he has made a full recovery and is now looking for a quiet home where he can be the center of attention.', 'Recovered - Fully healed from injuries', 'Under Care', '2024-04-05'),
('Bella', 'Dog', 'Labrador Mix', 1, '🐕', 'Bella was part of a litter found in an abandoned building. She was the smallest of the group but has grown into an energetic, loving puppy who would thrive in an active family.', 'Healthy - Age-appropriate vaccinations', 'Adopted', '2024-05-12'),
('Shadow', 'Cat', 'Domestic Longhair', 6, '🐱', 'Shadow lived as a stray for years before being brought to us by a kind neighbor. She is a gentle senior cat looking for a peaceful retirement home where she can enjoy her golden years.', 'Senior care needs - Regular checkups needed', 'Available', '2024-06-18');