// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxrpvmtfpzouaugcdczu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4cnB2bXRmcHpvdWF1Z2NkY3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTc2MjMsImV4cCI6MjA3MTQzMzYyM30.w9ac3rA7ZXVX3U98DTO_4vbc0dMb80a7ECF1qK_2Yvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});